[openproject]
exclude_projects = [
    "Leviia",
    "Administration Système",
    # "AdminSys Run",
    # "AdminSys Projets",
    "Développement",
    "Certification ISO 27001 & HDS"
]
exclude_users = [
    "admin-sys@leviia.com",
    "contact@leviia.com"
]

[plane]
exclude_users = [
    "admin-sys@leviia.com"
]
include_statuses = [
    "Backlog",
    "Todo",
    "In Progress",
    "Done",
    "Unscoped",
    "Cancelled",
    "In Review",
    "Duplicated"
]