[openproject]
exclude_projects = [
    "Leviia",
    "Administration Système",
    "Développement",
    "Certification ISO 27001 & HDS"
]
exclude_users = [
    "admin-sys@leviia.com",
    "contact@leviia.com"
]

[plane]
exclude_users = [
    "admin-sys@leviia.com"
]